[2024-10-12T17:08:48.184+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-12T17:08:48.201+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Nikita_Lapshin_experiment.train_and_log_model scheduled__2024-10-11T01:00:00+00:00 [queued]>
[2024-10-12T17:08:48.208+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Nikita_Lapshin_experiment.train_and_log_model scheduled__2024-10-11T01:00:00+00:00 [queued]>
[2024-10-12T17:08:48.209+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-10-12T17:08:48.219+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_and_log_model> on 2024-10-11 01:00:00+00:00
[2024-10-12T17:08:48.231+0000] {standard_task_runner.py:64} INFO - Started process 478 to run task
[2024-10-12T17:08:48.239+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Nikita_Lapshin_experiment', 'train_and_log_model', 'scheduled__2024-10-11T01:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/HW2.py', '--cfg-path', '/tmp/tmpr01j98mt']
[2024-10-12T17:08:48.242+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask train_and_log_model
[2024-10-12T17:08:48.329+0000] {task_command.py:426} INFO - Running <TaskInstance: Nikita_Lapshin_experiment.train_and_log_model scheduled__2024-10-11T01:00:00+00:00 [running]> on host 8027b3e99bd6
[2024-10-12T17:08:48.449+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lapshin Nikita' AIRFLOW_CTX_DAG_ID='Nikita_Lapshin_experiment' AIRFLOW_CTX_TASK_ID='train_and_log_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-11T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-11T01:00:00+00:00'
[2024-10-12T17:08:48.452+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-12T17:08:48.477+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket mlops-2 with path datasets/prepared_data.csv
[2024-10-12T17:08:48.494+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-12T17:08:48.494+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-12T17:09:51.908+0000] {logging_mixin.py:188} WARNING - 2024/10/12 17:09:51 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-10-12T17:10:11.455+0000] {local_task_job_runner.py:243} INFO - Task exited with return code -9For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2024-10-12T17:10:11.667+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-12T17:10:11.668+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
